directories:
  output: nsis
  buildResources: build
appId: com.get174.glockcleaner
productName: GlockCleaner
files:
  - filter:
      - '**/*'
      - '!dist/**/*'
win:
  target: nsis-web
  icon: build/installerIcon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerIcon: assets/installerIcon.ico
  installerSidebar: assets/installerSidebar.bmp
  installerHeader: assets/installerHeader.bmp
  uninstallerSidebar: assets/uninstallerSidebar.bmp
publish:
  provider: github
  owner: get174
  repo: glockcleaner
extraResources:
  - from: assets
    to: assets
electronVersion: 41.5.1
