directories:
  output: nsis
  buildResources: build
appId: com.get174.glockcleaner
productName: GlockCleaner
files:
  - filter:
      - '**/*'
      - '!dist/**/*'
win:
  target: nsis-web
  icon: build/installerIcon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerIcon: build/installerIcon.ico
  installerSidebar: build/installerSidebar.bmp
  installerHeader: build/installerHeader.bmp
  uninstallerSidebar: build/uninstallerSidebar.bmp
publish:
  provider: github
  owner: get174
  repo: glockcleaner
electronVersion: 41.5.1
